apiVersion: skaffold/v2alpha3
kind: Config
deploy:
  kubectl:
    manifests:
      - ./infra/k8s/*
build:
  local:
    push: false
  # googleCloudBuild:
  #   projectId: ta-vrilance-cluster
  artifacts:
    - image: rommycy00/ta-auth
      context: ta-auth
      docker: 
        dockerfile: Dockerfile
      sync:
        manual:
          - src: 'src/**/*.ts'
            dest: .
    - image: rommycy00/ta-client
      context: ta-client
      docker: 
        dockerfile: Dockerfile
      sync:
        manual:
          - src: '**/*.js'
            dest: .
    - image: rommycy00/ta-jobs-category
      context: ta-jobs-category
      docker: 
        dockerfile: Dockerfile
      sync:
        manual:
          - src: '**/*.ts'
            dest: .
    - image: rommycy00/ta-expiration
      context: ta-expiration
      docker: 
        dockerfile: Dockerfile
      sync:
        manual:
          - src: 'src/**/*.ts'
            dest: .
    - image: rommycy00/ta-orders
      context: ta-orders
      docker: 
        dockerfile: Dockerfile
      sync:
        manual:
          - src: '**/*.ts'
            dest: .
    - image: rommycy00/ta-rating-review
      context: ta-rating-review
      docker: 
        dockerfile: Dockerfile
      sync:
        manual:
          - src: '**/*.ts'
            dest: .
    - image: rommycy00/ta-search-recommendations
      context: ta-search-recommendations
      docker: 
        dockerfile: Dockerfile
      sync:
        manual:
          - src: '**/*.ts'
            dest: .
    # - image: us.gcr.io/ta-vrilance-cluster/ta-auth
    #   context: ta-auth
    #   docker: 
    #     dockerfile: Dockerfile
    #   sync:
    #     manual:
    #       - src: 'src/**/*.ts'
    #         dest: .
    # - image: us.gcr.io/ta-vrilance-cluster/ta-client
    #   context: ta-client
    #   docker: 
    #     dockerfile: Dockerfile
    #   sync:
    #     manual:
    #       - src: '**/*.js'
    #         dest: .
    # - image: us.gcr.io/ta-vrilance-cluster/ta-jobs-category
    #   context: ta-jobs-category
    #   docker: 
    #     dockerfile: Dockerfile
    #   sync:
    #     manual:
    #       - src: '**/*.ts'
    #         dest: .
    # - image: us.gcr.io/ta-vrilance-cluster/ta-expiration
    #   context: ta-expiration
    #   docker: 
    #     dockerfile: Dockerfile
    #   sync:
    #     manual:
    #       - src: 'src/**/*.ts'
    #         dest: .
    # - image: us.gcr.io/ta-vrilance-cluster/ta-orders
    #   context: ta-orders
    #   docker: 
    #     dockerfile: Dockerfile
    #   sync:
    #     manual:
    #       - src: '**/*.ts'
    #         dest: .
    # - image: us.gcr.io/ta-vrilance-cluster/ta-rating-review
    #   context: ta-rating-review
    #   docker: 
    #     dockerfile: Dockerfile
    #   sync:
    #     manual:
    #       - src: '**/*.ts'
    #         dest: .